### ISSUE TITLE
Extension does not hide watched videos

### ISSUE THREAD

**Issue by MelvinLoos** [matt0x5B/HideYoutubeWatchedVideos-Issues#4]
**Describe the bug**
It does not hide videos, I tried switching the extension button from green to red, refreshing the page, nothing happens.

**Expected behavior**
I expect it to hide videos that I have already watched

**Screenshots**
![image](https://user-images.githubusercontent.com/1757355/187307050-61719d94-85fc-4fad-b925-36997abec81a.png)

**Browser (please complete the following information):**
 - Browser: [e.g. Chrome, Edge]
 - Version [e.g. 22] (Find this in Chrome: (Menu) ⋮ -> Help -> About Google Chrome) (Find this in Edge: (Menu) … -> Help and feedback -> About Microsoft Edge)
I am running Vivaldi which runs on chrome:

Vivaldi | 5.4.2753.40 (Stable channel) (64-bit)
-- | --
Revision | 1be992cf9ef1a9cc146552efd04513a8da739823
OS | Windows 10 Version 21H2 (Build 19044.1889)
JavaScript | V8 10.4.132.22
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.105 Safari/537.36

**Comment by matt0x5B** [comment]
@MelvinLoos Thank you for providing a screenshot and all information. I have been able to reproduce and will hopefully get a new version out soon with a fix.

**Comment by matt0x5B** [comment]
I have published a new version that should resolve this issue for you, version 1.6.7, I am not too sure how Vivaldi handles its extensions updates but if it does not automatically update to this version you may need to force it.

**Comment by MelvinLoos** [comment]
Awesome that's a great response time. I will test it when I get back from work!

**Comment by MelvinLoos** [comment]
Sorry took a bit longer but I just tested it and it works again, thanks!
